#!/usr/bin/env python3

import yaml
from charmhelpers.core import hookenv

with open('resources.yaml') as fp:
    resources = yaml.load(fp)

vxa = {}
for res in resources['optional_resources'].keys():
    if 'hadoop-' not in res or 'lzo' in res or res.count('-') != 2:
        continue
    _, version, arch = res.split('-')
    arch = arch.replace('_', '-')
    vxa.setdefault(arch, []).append(version)

for arch, vers in vxa.items():
    hookenv.action_set({arch: yaml.dump(vers)})
